"""
Scanner cache self-heal — scanner_cache.json is gitignored (regenerated by a
scan, not shipped in the repo) and only refreshed by a weekly cron. On a host
with an ephemeral filesystem, every restart can wipe it and leave the
Portfolio Simulator's recommendation engine (and the scanner itself) starved
indefinitely between cron windows. cache_needs_refresh() is what lets
main.py's startup self-heal instead of only waiting for Monday 02:00 UTC.

Run: venv/bin/python -m pytest tests/test_scanner_cache_refresh.py -q   (from backend/)
"""

import os
import sys
from datetime import datetime, timedelta, timezone
from unittest.mock import patch

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault("SUPABASE_JWT_SECRET", "test-secret-for-pytest")

from routers.scanner import cache_needs_refresh


def test_missing_cache_needs_refresh():
    with patch("routers.scanner._read_cache", return_value=None):
        assert cache_needs_refresh() is True


def test_corrupt_cache_without_last_updated_needs_refresh():
    with patch("routers.scanner._read_cache", return_value={"results": []}):
        assert cache_needs_refresh() is True


def test_unparseable_last_updated_needs_refresh():
    with patch("routers.scanner._read_cache", return_value={"last_updated": "not-a-date"}):
        assert cache_needs_refresh() is True


def test_fresh_cache_does_not_need_refresh():
    now = datetime.now(timezone.utc).isoformat()
    with patch("routers.scanner._read_cache", return_value={"last_updated": now}):
        assert cache_needs_refresh(max_age_hours=1) is False


def test_stale_cache_needs_refresh():
    old = (datetime.now(timezone.utc) - timedelta(days=10)).isoformat()
    with patch("routers.scanner._read_cache", return_value={"last_updated": old}):
        assert cache_needs_refresh(max_age_hours=24 * 7) is True


def test_naive_timestamp_treated_as_utc():
    # A naive ISO string (no tzinfo) must not crash the comparison.
    now_naive = datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
    with patch("routers.scanner._read_cache", return_value={"last_updated": now_naive}):
        assert cache_needs_refresh(max_age_hours=1) is False
